owner: vhynlain
repo: uptime-vhynlain.com
user-agent: vhynlain-uptime

sites:
  - name: vhynlain.com
    url: https://vhynlain.com

status-website:
  cname: status.vhynlain.com
  name: Vhynlain Status

i18n:
  footer: "Powered by Upptime"

delay: 300
maxResponseTime: 60
daysUntilStale: 90
